name: Deploy GH Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: lts/*
          registry-url: https://npm.pkg.github.com
          scope: '@tuxmart'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - name: Deploy
        run: pnpm deploy
